export enum Module {
  manage = 'manage',
  onboarding = 'onboarding',
  createCompany = 'createCompany',
  uploadCompanyLicense = 'uploadCompanyLicense',
  createBranch = 'createBranch',
  createEmployee = 'createEmployee',
  companyManagement = 'companyManagement',
  branchManagement = 'branchManagement',
  departmentManagement = 'departmentManagement',
  employeeManagement = 'employeeManagement',
  profile = 'profile',
  shared = 'shared',
}

export enum SubModule {
  flows = 'flows',
  companyOnboarding = 'companyOnboarding',
  employeeOnboarding = 'employeeOnboarding',
  companyDetails = 'companyDetails',
  companyViewDetails = 'companyViewDetails',
  companyLicenseDetails = 'companyLicenseDetails',
  companyLicenseViewDetails = 'companyLicenseViewDetails',
  branchCatalog = 'branchCatalog',
  branchDetails = 'branchDetails',
  branchViewDetails = 'branchViewDetails',
  branchLocationDetails = 'branchLocationDetails',
  departmentCatalog = 'departmentCatalog',
  departmentDetails = 'departmentDetails',
  departmentViewDetails = 'departmentViewDetails',
  employeeCatalog = 'employeeCatalog',
  employeeDetails = 'employeeDetails',
  employeeViewDetails = 'employeeViewDetails',
  profileDetails = 'profileDetails',
  profileViewDetails = 'profileViewDetails',
  profileViewSettings = 'profileViewSettings',
  notFound = 'notFound',
  snackbar = 'snackbar',
  license = 'license',
  upload = 'upload',
  header = 'header',
  menu = 'menu',
}
