export enum Module {
  manage = 'manage',
  companySetup = 'companySetup',
  branchSetup = 'branchSetup',
  employeeSetup = 'employeeSetup',
  companyManagement = 'companyManagement',
  branchManagement = 'branchManagement',
  departmentManagement = 'departmentManagement',
  employeeManagement = 'employeeManagement',
  profile = 'profile',
  shared = 'shared',
}

export enum SubModule {
  flows = 'flows',
  companyDetails = 'companyDetails',
  companyViewDetails = 'companyViewDetails',
  companyLicenseViewDetails = 'companyLicenseViewDetails',
  branchTable = 'branchTable',
  branchDetails = 'branchDetails',
  branchViewDetails = 'branchViewDetails',
  branchLocationDetails = 'branchLocationDetails',
  departmentCatalog = 'departmentCatalog',
  departmentDetails = 'departmentDetails',
  departmentViewDetails = 'departmentViewDetails',
  employeeTable = 'employeeTable',
  employeeDetails = 'employeeDetails',
  employeeViewDetails = 'employeeViewDetails',
  profileDetails = 'profileDetails',
  profileViewDetails = 'profileViewDetails',
  profileViewSettings = 'profileViewSettings',
  notFound = 'notFound',
  snackbar = 'snackbar',
  license = 'license',
  upload = 'upload',
  header = 'header',
  menu = 'menu',
}
